[[partner3]]
name = "SODA Lab"
logo = "images/initiators/soda_sub1.png"
url = "https://www.stat.lmu.de/soda/en/home.html"

[[partner3]]
name = "LMU Munich"
logo = "images/initiators/Logo_LMU.svg"
url = "https://www.lmu.de"

[[partner2]]
name = "Bayerische Staatsministerium für Digitales"
logo = "images/initiators/Logo_StMD2.png"
url = "https://www.stmd.bayern.de"